name: Broken link check
on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@v1.0.0
      with:
        url: 'https://github.com/celinekurpershoek/github-actions-link-checker'
        honorRobotExclusions: true
        ignorePatterns: 'github'
    - name: Get the result
      - shell: bash
        run: steps.link-report.outputs.result > actions/link-result.txt
      - name: Upload link report results
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: link-results.txt

  job2:
    - name: Comment results on PR
      runs-on: ubuntu-latest
      uses: mshick/add-pr-comment@v1
      needs: job1
      steps:
      - name: Download link-results
        uses: actions/download-artifact@v1
        with:
          name: results
      - name: Comment results
      with:
        message: |
          **Hello**
          ğŸŒ
          !
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-repeats: false  
