on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links on domain
    steps:
    - name: Check links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@master
      with:
        url: 'https://voorhoede.nl'
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"